services:
  - type: web
    name: portfolio-backend
    env: python311
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT server:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        sync: false
      - key: BASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://kienportfolio.onrender.com,https://dangtrungkien.online,https://www.dangtrungkien.online
        sync: false
